# Generated by Django 4.0.4 on 2022-07-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suma',
            name='Cena1B',
            field=models.IntegerField(default=130),
        ),
        migrations.AddField(
            model_name='suma',
            name='Cena2A',
            field=models.IntegerField(default=110),
        ),
        migrations.AddField(
            model_name='suma',
            name='CenaS',
            field=models.IntegerField(default=1900),
        ),
        migrations.AddField(
            model_name='suma',
            name='CenaSS',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='suma',
            name='Ilosc1B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suma',
            name='Ilosc2A',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suma',
            name='IloscS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suma',
            name='IloscSS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suma',
            name='Suma1B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suma',
            name='Suma2A',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suma',
            name='SumaS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suma',
            name='SumaSS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suma',
            name='Sumaogolna',
            field=models.IntegerField(default=0),
        ),
    ]
