# Generated by Django 4.0.4 on 2022-07-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0003_alter_suma_cenas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie', models.CharField(max_length=300)),
                ('Nazwisko', models.CharField(max_length=300)),
            ],
        ),
    ]
