# Generated by Django 4.0.4 on 2022-07-01 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0004_klient'),
    ]

    operations = [
        migrations.AddField(
            model_name='suma',
            name='klient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazyn.klient'),
        ),
    ]
