# Generated by Django 4.0.4 on 2022-07-01 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0006_klient_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='suma',
            name='DataZamowienia',
            field=models.DateField(default=datetime.date(2022, 7, 1)),
        ),
    ]
