# Generated by Django 4.0.4 on 2022-07-04 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0010_alter_kurnikprodukcja_kurnik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='Data',
            field=models.DateField(default=datetime.date(2022, 7, 4)),
        ),
        migrations.AlterField(
            model_name='kurnikprodukcja',
            name='Dataprodukcji',
            field=models.DateField(default=datetime.date(2022, 7, 4)),
        ),
        migrations.AlterField(
            model_name='kurnikprodukcja',
            name='Kurnik',
            field=models.CharField(choices=[('Kurnik K1', 'Kurnik K1'), ('Kurnik K3', 'Kurnik K3')], default='Kurnik K3', max_length=10),
        ),
        migrations.AlterField(
            model_name='suma',
            name='DataZamowienia',
            field=models.DateField(default=datetime.date(2022, 7, 4)),
        ),
    ]
