# Generated by Django 4.0.4 on 2022-07-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0012_kurnikprodukcja_uwagi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurnikprodukcja',
            name='upadki',
            field=models.IntegerField(default=0),
        ),
    ]
