# Generated by Django 4.0.4 on 2022-07-04 14:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0013_kurnikprodukcja_upadki'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurnikprodukcja',
            name='Uwagi',
        ),
        migrations.RemoveField(
            model_name='kurnikprodukcja',
            name='upadki',
        ),
        migrations.AlterField(
            model_name='klient',
            name='Data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='kurnikprodukcja',
            name='Dataprodukcji',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='suma',
            name='DataZamowienia',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Uwagi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uwagi', models.CharField(blank=True, max_length=300)),
                ('upadki', models.IntegerField(default=0)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('kurnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazyn.kurnikprodukcja')),
            ],
        ),
    ]
