# Generated by Django 4.0.4 on 2022-07-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0014_remove_kurnikprodukcja_uwagi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uwagi',
            name='kurnik',
            field=models.CharField(choices=[('Kurnik K1', 'Kurnik K1'), ('Kurnik K3', 'Kurnik K3')], default='Kurnik K3', max_length=10),
        ),
    ]
